name: Workflow ej1

on: push

jobs:
  onPush:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        run: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Probar código
        run: pytest test.py
